# Generated by Django 3.2.8 on 2022-09-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persoana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('surname', models.CharField(default='', max_length=15)),
                ('user', models.CharField(default='', max_length=12)),
                ('password', models.CharField(default='', max_length=12)),
                ('canUpload', models.BooleanField(default=True)),
                ('canDownload', models.BooleanField(default=False)),
            ],
        ),
    ]
