# Generated by Django 3.2.8 on 2023-07-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persoana',
            new_name='Person',
        ),
    ]
