# Generated by Django 3.2.8 on 2022-07-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_persoana_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='persoana',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
