# Generated by Django 3.2.8 on 2022-07-22 16:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_persoana_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilet',
            name='code',
            field=models.CharField(default=api.models.gen_code, max_length=8, unique=True),
        ),
    ]
